{
  imports = [
    ./accounts
    ./firefox
    ./ncmpcpp
    ./neovim/neovim.nix
    ./2bwm.nix
    ./alacritty.nix
    ./awesomewm.nix
    # ./bash.nix
    ./bspwm.nix
    ./devops.nix
    ./git.nix
    ./gnu.nix
    ./herbstluftwm.nix
    ./newsboat.nix
    ./rofi.nix
    ./spotify.nix
    ./starship.nix
    ./texlive.nix
    ./thunar.nix
    ./tmux.nix
    ./urxvt.nix
    ./vencord.nix
    ./vscode.nix
    ./wezterm.nix
    ./zathura.nix
    ./zsh.nix
  ];
}
