{
  imports = [
    ./accounts
    ./awesome
    ./devops
    ./firefox
    ./ncmpcpp
    ./neovim
    ./vscode
    ./2bwm.nix
    ./alacritty.nix
    ./atuin.nix
    ./bash.nix
    ./bitwarden.nix
    ./bspwm.nix
    ./chromium.nix
    ./fetch.nix
    ./git.nix
    ./gnu.nix
    ./herbstluftwm.nix
    ./mpv.nix
    ./newsboat.nix
    ./rofi.nix
    ./spotify.nix
    ./ssh.nix
    ./starship.nix
    ./texlive.nix
    ./thunar.nix
    ./tmux.nix
    ./urxvt.nix
    ./vencord.nix
    ./wezterm.nix
    ./yt-dlp.nix
    ./zathura.nix
    ./zed-editor.nix
    ./zsh.nix
  ];
}
