{ theme, ... }:

with theme;

let
  name = "default";
in
{
  home.file.".config/nvim/colors/${name}.lua".text = ''
    vim.cmd("highlight clear")

    if vim.fn.exists("syntax_on") then
        vim.cmd("syntax reset")
    end

    vim.g.colors_name = "${name}"
    vim.o.background = "dark"
    vim.o.termguicolors = true

    local c = {
      base00 = "${base00}",
      base01 = "${base01}",
      base02 = "${base02}",
      base03 = "${base03}",
      base04 = "${base04}",
      base05 = "${base05}",
      base06 = "${base06}",
      base07 = "${base07}",
      base08 = "${base08}",
      base09 = "${base09}",
      base0A = "${base0A}",
      base0B = "${base0B}",
      base0C = "${base0C}",
      base0D = "${base0D}",
      base0E = "${base0E}",
      base0F = "${base0F}",
    }

    local function highlight(group, opts)
      if opts.link then
        local link_attrs = vim.api.nvim_get_hl(0, { name = opts.link, link = false }) or {}
        local new_opts = vim.tbl_deep_extend("force", {}, link_attrs, opts)
        new_opts.link = nil
        vim.api.nvim_set_hl(0, group, new_opts)
      else
        vim.api.nvim_set_hl(0, group, opts)
      end
    end

    -- Base Theme
    highlight("Normal", { fg = c.base04, bg = c.base00 })
    highlight("NormalFloat", { fg = c.base05, bg = c.base01 })
    highlight("NormalNC", { fg = c.base04, bg = c.base00 })
    highlight("ColorColumn", { bg = c.base01 })
    highlight("Conceal", {})
    highlight("Cursor", { fg = c.base00, bg = c.base04 })
    highlight("lCursor", { fg = c.base00, bg = c.base04 })
    highlight("CursorIM", { fg = c.base00, bg = c.base04 })
    highlight("CursorColumn", { bg = c.base01 })
    highlight("CursorLine", { bg = c.base01 })
    highlight("Directory", { fg = c.base08 })
    highlight("DiffAdd", { fg = c.base00, bg = c.base0D })
    highlight("DiffChange", { fg = c.base00, bg = c.base09 })
    highlight("DiffDelete", { fg = c.base00, bg = c.base0A })
    highlight("DiffText", { fg = c.base00, bg = c.base08 })
    highlight("DiffAdded", { fg = c.base07 })
    highlight("DiffChanged", { fg = c.base09 })
    highlight("DiffRemoved", { fg = c.base0A })
    highlight("EndOfBuffer", { fg = c.base01 })
    highlight("ErrorMsg", { fg = c.base0A })
    highlight("NvimInternalError", { fg = c.base00, bg = c.base08 })
    highlight("VertSplit", { fg = c.base01, bg = c.base00 })
    highlight("WinSeparator", { fg = c.base01, bg = c.base00 })
    highlight("Folded", { fg = c.base02, bg = c.base01 })
    highlight("FoldColumn", { fg = c.base01, bg = c.base00 })
    highlight("SignColumn", { fg = c.base01, bg = c.base00 })
    highlight("IncSearch", { fg = c.base06, bg = c.base0A })
    highlight("Substitute", { fg = c.base01, bg = c.base08 })
    highlight("LineNr", { fg = c.base03, bg = c.base00 })
    highlight("CursorLineNr", { fg = c.base04 })
    highlight("MatchParen", { bg = c.base02, underline = true })
    highlight("ModeMsg", { fg = c.base04 })
    highlight("MsgArea", { fg = c.base05 })
    highlight("MsgSeparator", { fg = c.base03 })
    highlight("MoreMsg", { fg = c.base08 })
    highlight("NonText", { fg = c.base02 })
    highlight("Pmenu", { fg = c.base04, bg = c.base01 })
    highlight("PmenuSel", { fg = c.base08, bg = c.base02 })
    highlight("PmenuSbar", { fg = c.base04, bg = c.base01 })
    highlight("PmenuThumb", { fg = c.base08, bg = c.base02 })
    highlight("PmenuKind", { fg = c.base08 })
    highlight("PmenuKindSel", { fg = c.base08 })
    highlight("PmenuExtra", { fg = c.base06, bg = c.base01 })
    highlight("PmenuExtraSel", { fg = c.base0B, bg = c.base02, bold = true })
    highlight("PmenuMatch", { fg = c.base0A, bold = true })
    highlight("Question", { fg = c.base04 })
    highlight("QuickFixLine", { bg = c.base01 })
    highlight("Search", { fg = c.base01, bg = c.base08 })
    highlight("CurSearch", { fg = c.base01, bg = c.base0B })
    highlight("SpecialKey", { fg = c.base03 })
    highlight("SpellBad", { sp = c.base0A, undercurl = true })
    highlight("SpellCap", { sp = c.base08, undercurl = true })
    highlight("SpellLocal", { sp = c.base0C, undercurl = true })
    highlight("SpellRare", { sp = c.base0E, undercurl = true })
    highlight("StatusLine", { fg = c.base04, bg = c.base00 })
    highlight("StatusLineNC", { fg = c.base04, bg = c.base01 })
    highlight("TabLine", { link = "StatusLineNC" })
    highlight("TabLineFill", { link = "TabLine" })
    highlight("TabLineSel", { link = "StatusLine" })
    highlight("Terminal", { fg = c.base05 })
    highlight("TermCursor", { fg = c.base00, bg = c.base04 })
    highlight("TermCursorNC", { fg = c.base00, bg = c.base04 })
    highlight("Title", { fg = c.base04 })
    highlight("Visual", { bg = c.base02 })
    highlight("VisualNOS", { bg = c.base02 })
    highlight("WarningMsg", { fg = c.base0E })
    highlight("Whitespace", { fg = c.base03 })
    highlight("WildMenu", { fg = c.base08, bg = c.base01 })
    highlight("WinBar", { fg = c.base04, bg = c.base00 })
    highlight("WinBarNC", { fg = c.base04, bg = c.base01 })
    highlight("FloatBorder", { fg = c.base01, bg = c.base01 })
    highlight("FloatTitle", { fg = c.base04 })

    -- Basic UI/Formatting Extras
    highlight("TooLong", { bg = c.base02 })
    highlight("Debug", { fg = c.base0D })
    highlight("Bold", { bold = true })
    highlight("Italic", { italic = true })
    highlight("Underlined", { underline = true })

    -- Core Syntax
    highlight("Boolean", { fg = c.base09 })
    highlight("Character", { fg = c.base0E })
    highlight("Comment", { fg = c.base03, italic = true })
    highlight("Conditional", { fg = c.base09 })
    highlight("Constant", { fg = c.base04 })
    highlight("Define", { fg = c.base09 })
    highlight("Delimiter", { fg = c.base06 })
    highlight("Error", { fg = c.base0A, bg = c.base01 })
    highlight("Exception", { fg = c.base09 })
    highlight("Float", { link = "Number" })
    highlight("Function", { fg = c.base0C })
    highlight("Identifier", { fg = c.base04 })
    highlight("Include", { fg = c.base09 })
    highlight("Keyword", { fg = c.base0E })
    highlight("Label", { fg = c.base09 })
    highlight("Macro", { fg = c.base07 })
    highlight("Number", { fg = c.base0A })
    highlight("Operator", { fg = c.base09 })
    highlight("PreCondit", { fg = c.base09 })
    highlight("PreProc", { fg = c.base09 })
    highlight("Repeat", { fg = c.base09 })
    highlight("Special", { fg = c.base04 })
    highlight("SpecialChar", { fg = c.base04 })
    highlight("SpecialComment", { fg = c.base08 })
    highlight("Statement", { fg = c.base09 })
    highlight("StorageClass", { fg = c.base09 })
    highlight("String", { fg = c.base0B })
    highlight("Structure", { fg = c.base09 })
    highlight("Tag", { fg = c.base04 })
    highlight("Todo", { fg = c.base0D })
    highlight("Type", { fg = c.base04 })
    highlight("Typedef", { fg = c.base09 })

    -- Help Pages
    highlight("helpHyperTextJump", { fg = c.base08 })
    highlight("helpSpecial", { fg = c.base09 })
    highlight("helpHeadline", { fg = c.base0A })
    highlight("helpHeader", { fg = c.base0F })

    -- TreeSitter standard
    highlight("@boolean", { link = "Boolean" })
    highlight("@character", { link = "Character" })
    highlight("@number", { link = "Number" })
    highlight("@number.float", { link = "Float" })
    highlight("@string", { link = "String" })
    highlight("@string.escape", { fg = c.base0F })
    highlight("@string.special", { link = "SpecialChar" })
    highlight("@string.regexp", { fg = c.base07 })
    highlight("@function", { link = "Function" })
    highlight("@function.call", { link = "Function" })
    highlight("@function.builtin", { fg = c.base0C })
    highlight("@function.macro", { fg = c.base07 })
    highlight("@constructor", { fg = c.base09 })
    highlight("@method", { fg = c.base0D })
    highlight("@method.call", { fg = c.base0C })
    highlight("@keyword", { fg = c.base09 })
    highlight("@keyword.function", { fg = c.base08 })
    highlight("@keyword.return", { fg = c.base09 })
    highlight("@keyword.repeat", { fg = c.base09 })
    highlight("@keyword.conditional", { fg = c.base09 })
    highlight("@keyword.exception", { fg = c.base09 })
    highlight("@keyword.import", { fg = c.base09 })
    highlight("@keyword.operator", { fg = c.base08 })
    highlight("@variable", { fg = c.base06 })
    highlight("@variable.builtin", { fg = c.base04 })
    highlight("@variable.parameter", { fg = c.base03 })
    highlight("@variable.member", { fg = c.base04 })
    highlight("@constant", { fg = c.base0E })
    highlight("@constant.builtin", { fg = c.base07 })
    highlight("@constant.macro", { fg = c.base07 })
    highlight("@type", { link = "Type" })
    highlight("@type.builtin", { link = "Type" })
    highlight("@type.definition", { link = "Typedef" })
    highlight("@type.qualifier", { link = "StorageClass" })
    highlight("@module", { fg = c.base07 })
    highlight("@module.builtin", { fg = c.base07 })
    highlight("@property", { fg = c.base07 })
    highlight("@attribute", { fg = c.base0F })
    highlight("@operator", { link = "Operator" })
    highlight("@punctuation.delimiter", { fg = c.base08 })
    highlight("@punctuation.bracket", { fg = c.base08 })
    highlight("@punctuation.special", { fg = c.base08 })
    highlight("@tag", { fg = c.base09 })
    highlight("@tag.delimiter", { fg = c.base0F })
    highlight("@tag.attribute", { fg = c.base0F })
    highlight("@comment", { link = "Comment" })
    highlight("@comment.todo", { link = "Todo" })
    highlight("@comment.warning", { fg = c.base0E, bold = true })
    highlight("@comment.error", { fg = c.base0A, bold = true })
    highlight("@comment.note", { fg = c.base09, bold = true })

    -- Missing TreeSitter & Language extensions
    highlight("@text.literal.commodity", { fg = c.base0D })
    highlight("@number.date", { fg = c.base08 })
    highlight("@number.date.effective", { fg = c.base0D })
    highlight("@number.interval", { fg = c.base09 })
    highlight("@number.status", { fg = c.base0C })
    highlight("@number.quantity", { fg = c.base0B })
    highlight("@number.quantity.negative", { fg = c.base0A })
    highlight("@error", { fg = c.base0B })
    highlight("@string.regex", { fg = c.base07 })
    highlight("@float", { link = "Float" })
    highlight("@conditional", { fg = c.base09 })
    highlight("@repeat", { fg = c.base09 })
    highlight("@label", { fg = c.base0F })
    highlight("@include", { fg = c.base09 })
    highlight("@exception", { fg = c.base0F })
    highlight("@field", { fg = c.base04 })
    highlight("@namespace", { fg = c.base07 })
    highlight("@symbol", { fg = c.base0F, bold = true })
    highlight("@text", { fg = c.base04 })
    highlight("@text.strong", { fg = c.base04, bold = true })
    highlight("@text.emphasis", { fg = c.base0A, bold = true })
    highlight("@text.underline", { fg = c.base0A, underline = true })
    highlight("@text.strike", { fg = c.base0A, strikethrough = true })
    highlight("@text.title", { fg = c.base0A })
    highlight("@text.literal", { fg = c.base04 })
    highlight("@text.uri", { fg = c.base0E, underline = true })
    highlight("@tag.builtin.tsx", { link = "@tag" })
    highlight("@reference", { fg = c.base04 })

    -- TreeSitter Markup (Markdown/HTML)
    highlight("@markup", { link = "Normal" })
    highlight("@markup.strong", { bold = true })
    highlight("@markup.italic", { italic = true })
    highlight("@markup.heading", { link = "Title" })
    highlight("@markup.raw", { link = "String" })
    highlight("@markup.link", { link = "markdownUrl" })
    highlight("@markup.link.url", { link = "markdownUrl" })
    highlight("@markup.list", { link = "markdownListMarker" })
    highlight("@markup.quote", { link = "markdownBlockquote" })
    highlight("@markup.environment", { link = "Macro" })
    highlight("@markup.environment.name", { link = "Type" })
    highlight("@markup.emphasis", { italic = true })
    highlight("@markup.strikethrough", { strikethrough = true })
    highlight("@markup.underline", { underline = true })
    highlight("@markup.heading.marker", { link = "markdownHeadingDelimiter" })
    highlight("@markup.heading.1.markdown", { link = "markdownH1" })
    highlight("@markup.heading.2.markdown", { link = "markdownH1" })
    highlight("@markup.heading.3.markdown", { link = "markdownH1" })
    highlight("@markup.heading.4.markdown", { link = "markdownH1" })
    highlight("@markup.heading.5.markdown", { link = "markdownH1" })
    highlight("@markup.heading.6.markdown", { link = "markdownH1" })
    highlight("@markup.heading.7.markdown", { link = "markdownH1" })
    highlight("@markup.heading.8.markdown", { link = "markdownH1" })
    highlight("@markup.link.label", { underline = true })
    highlight("@markup.link.label.symbol", { link = "markdownItalic" })
    highlight("@markup.link.label.markdown_inline", { link = "markdownItalic" })
    highlight("@markup.link.title", { link = "Title" })
    highlight("@markup.link.destination", { link = "markdownUrl" })
    highlight("@markup.link.description", { fg = c.base01, underline = true, italic = true })
    highlight("@markup.list.bullet", { link = "markdownListMarker" })
    highlight("@markup.list.checked", { link = "markdownListMarker" })
    highlight("@markup.list.markdown", { link = "markdownListMarker" })
    highlight("@markup.list.ordered", { link = "markdownOrderedListMarker" })
    highlight("@markup.list.unchecked", { link = "markdownListMarker" })
    highlight("@markup.math", { link = "Special" })
    highlight("@markup.raw.markdown_inline", { link = "String" })
    highlight("@markup.literal", { link = "markdownCode" })
    highlight("@markup.code.block", { link = "markdownCodeBlock" })
    highlight("@markup.rule", { link = "Comment" })

    -- Markdown standard groups
    highlight("markdownBlockquote", { fg = c.base08 })
    highlight("markdownBold", { link = "Bold" })
    highlight("markdownItalic", { link = "Italic" })
    highlight("markdownBoldItalic", { bold = true, italic = true })
    highlight("markdownRule", { link = "Comment" })
    highlight("markdownH1", { fg = c.base0A })
    highlight("markdownH2", { link = "markdownH1" })
    highlight("markdownH3", { link = "markdownH1" })
    highlight("markdownH4", { link = "markdownH1" })
    highlight("markdownH5", { link = "markdownH1" })
    highlight("markdownH6", { link = "markdownH1" })
    highlight("markdownHeadingDelimiter", { link = "markdownH1" })
    highlight("markdownHeadingRule", { link = "markdownH1" })
    highlight("markdownUrl", { fg = c.base0E, underline = true })
    highlight("markdownCode", { link = "String" })
    highlight("markdownCodeBlock", { link = "markdownCode" })
    highlight("markdownCodeDelimiter", { link = "markdownCode" })
    highlight("markdownListMarker", { fg = c.base08 })
    highlight("markdownOrderedListMarker", { fg = c.base08 })

    -- LSP / Diagnostics Core
    highlight("DiagnosticError", { fg = c.base0A })
    highlight("DiagnosticWarn", { fg = c.base0E })
    highlight("DiagnosticInfo", { fg = c.base09 })
    highlight("DiagnosticHint", { fg = c.base04 })
    highlight("DiagnosticOk", { fg = c.base0D })
    highlight("DiagnosticSignError", { fg = c.base0A })
    highlight("DiagnosticSignWarn", { fg = c.base0E })
    highlight("DiagnosticSignInfo", { fg = c.base09 })
    highlight("DiagnosticSignHint", { fg = c.base04 })
    highlight("DiagnosticFloatingError", { fg = c.base0A })
    highlight("DiagnosticFloatingWarn", { fg = c.base0E })
    highlight("DiagnosticFloatingInfo", { fg = c.base09 })
    highlight("DiagnosticFloatingHint", { fg = c.base04 })
    highlight("DiagnosticVirtualTextError", { fg = c.base0A })
    highlight("DiagnosticVirtualTextWarn", { fg = c.base0E })
    highlight("DiagnosticVirtualTextInfo", { fg = c.base09 })
    highlight("DiagnosticVirtualTextHint", { fg = c.base04 })
    highlight("DiagnosticUnderlineError", { sp = c.base0A, undercurl = true })
    highlight("DiagnosticUnderlineWarn", { sp = c.base0E, undercurl = true })
    highlight("DiagnosticUnderlineInfo", { sp = c.base04, undercurl = true })
    highlight("DiagnosticUnderlineHint", { sp = c.base04, undercurl = true })
    highlight("HealthError", { fg = c.base0A })
    highlight("HealthWarning", { fg = c.base0E })
    highlight("HealthSuccess", { fg = c.base0D })

    -- LSP References
    highlight("LspReferenceText", { bg = c.base03 })
    highlight("LspReferenceRead", { bg = c.base03 })
    highlight("LspReferenceWrite", { bg = c.base03 })
    highlight("LspCodeLens", { bg = c.base03 })
    highlight("LspSignatureActiveParameter", { fg = c.base08 })

    -- Semantic Tokens
    highlight("@lsp.type.class", { link = "Structure" })
    highlight("@lsp.type.comment", { link = "@comment" })
    highlight("@lsp.type.decorator", { link = "Decorator" })
    highlight("@lsp.type.decorator.markdown", { link = "Structure" })
    highlight("@lsp.type.enum", { link = "@type" })
    highlight("@lsp.type.enumMember", { link = "@constant" })
    highlight("@lsp.type.function", { link = "Function" })
    highlight("@lsp.type.interface", { link = "@type" })
    highlight("@lsp.type.keyword", { link = "Keyword" })
    highlight("@lsp.type.macro", { link = "Macro" })
    highlight("@lsp.type.method", { link = "@method" })
    highlight("@lsp.type.namespace", { link = "@namespace" })
    highlight("@lsp.type.parameter", { link = "@parameter" })
    highlight("@lsp.type.property", { link = "@property" })
    highlight("@lsp.type.struct", { link = "Structure" })
    highlight("@lsp.type.type", { link = "@type" })
    highlight("@lsp.type.typeParameter", { link = "Typedef" })
    highlight("@lsp.type.variable", { link = "@variable" })
    highlight("@lsp.type.selfParameter", { link = "@variable.builtin" })
    highlight("@lsp.type.builtinConstant", { link = "@constant.builtin" })
    highlight("@lsp.type.magicFunction", { link = "@function.builtin" })
    highlight("@lsp.type.boolean", { link = "@boolean" })
    highlight("@lsp.type.builtinType", { link = "@type.builtin" })
    highlight("@lsp.type.escapeSequence", { link = "@string.escape" })
    highlight("@lsp.type.formatSpecifier", { link = "@punctuation.special" })
    highlight("@lsp.type.number", { link = "@number" })
    highlight("@lsp.type.operator", { link = "@operator" })
    highlight("@lsp.type.selfKeyword", { link = "@variable.builtin" })
    highlight("@lsp.type.string.rust", { link = "@string" })
    highlight("@lsp.type.typeAlias", { link = "@type.definition" })
    highlight("@lsp.type.unresolvedReference", { link = "Error" })
    highlight("@lsp.mod.readonly", { link = "@constant" })
    highlight("@lsp.mod.typeHint", { link = "Type" })
    highlight("@lsp.mod.builtin", { link = "Special" })
    highlight("@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
    highlight("@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
    highlight("@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
    highlight("@lsp.typemod.keyword.async", { link = "Keyword" })
    highlight("@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
    highlight("@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
    highlight("@lsp.typemod.operator.injected", { link = "@operator" })
    highlight("@lsp.typemod.string.injected", { link = "@string" })
    highlight("@lsp.typemod.operator.controlFlow", { link = "@exception" })
    highlight("@lsp.typemod.keyword.documentation", { link = "Special" })
    highlight("@lsp.typemod.variable.global", { link = "@constant" })
    highlight("@lsp.typemod.variable.static", { link = "@constant" })
    highlight("@lsp.typemod.function.builtin", { link = "@function.builtin" })
    highlight("@lsp.typemod.function.readonly", { link = "@method" })
    highlight("@lsp.typemod.variable.injected", { link = "@variable" })
    highlight("@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
    highlight("@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })

    -- nvim-cmp
    highlight("CmpItemAbbr", { fg = c.base04 })
    highlight("CmpItemAbbrMatch", { fg = c.base05, bold = true })
    highlight("CmpItemAbbrMatchFuzzy", { fg = c.base04, bold = true })
    highlight("CmpItemMenu", { fg = c.base04, italic = true })
    highlight("CmpItemKindInterface", { fg = c.base01, bg = c.base08 })
    highlight("CmpItemKindColor", { fg = c.base01, bg = c.base08 })
    highlight("CmpItemKindTypeParameter", { fg = c.base01, bg = c.base08 })
    highlight("CmpItemKindText", { fg = c.base01, bg = c.base09 })
    highlight("CmpItemKindEnum", { fg = c.base01, bg = c.base09 })
    highlight("CmpItemKindKeyword", { fg = c.base01, bg = c.base09 })
    highlight("CmpItemKindConstant", { fg = c.base01, bg = c.base0A })
    highlight("CmpItemKindConstructor", { fg = c.base01, bg = c.base0A })
    highlight("CmpItemKindReference", { fg = c.base01, bg = c.base0A })
    highlight("CmpItemKindFunction", { fg = c.base01, bg = c.base0B })
    highlight("CmpItemKindStruct", { fg = c.base01, bg = c.base0B })
    highlight("CmpItemKindClass", { fg = c.base01, bg = c.base0B })
    highlight("CmpItemKindModule", { fg = c.base01, bg = c.base0B })
    highlight("CmpItemKindOperator", { fg = c.base01, bg = c.base0B })
    highlight("CmpItemKindField", { fg = c.base01, bg = c.base0C })
    highlight("CmpItemKindProperty", { fg = c.base01, bg = c.base0C })
    highlight("CmpItemKindEvent", { fg = c.base01, bg = c.base0C })
    highlight("CmpItemKindUnit", { fg = c.base01, bg = c.base0D })
    highlight("CmpItemKindSnippet", { fg = c.base01, bg = c.base0D })
    highlight("CmpItemKindFolder", { fg = c.base01, bg = c.base0D })
    highlight("CmpItemKindVariable", { fg = c.base01, bg = c.base0E })
    highlight("CmpItemKindFile", { fg = c.base01, bg = c.base0E })
    highlight("CmpItemKindMethod", { fg = c.base01, bg = c.base0F })
    highlight("CmpItemKindValue", { fg = c.base01, bg = c.base0F })
    highlight("CmpItemKindEnumMember", { fg = c.base01, bg = c.base0F })

    -- blink.cmp
    highlight("BlinkCmpMenuBorder", { fg = c.base02, bg = c.base01 })
    highlight("BlinkCmpLabel", { fg = c.base04 })
    highlight("BlinkCmpLabelDepricated", { fg = c.base04, strikethrough = true })
    highlight("BlinkCmpLabelMatch", { fg = c.base08, bold = true })
    highlight("BlinkCmpGhostText", { fg = c.base02 })
    highlight("BlinkCmpKind", { bg = c.base00 })
    highlight("BlinkCmpKindText", { fg = c.base04 })
    highlight("BlinkCmpKindFunction", { fg = c.base08 })
    highlight("BlinkCmpKindProperty", { fg = c.base0D })
    highlight("BlinkCmpKindVariable", { fg = c.base0B })
    highlight("BlinkCmpKindEnum", { fg = c.base0A })
    highlight("BlinkCmpKindSnippet", { fg = c.base0C })
    highlight("BlinkCmpKindField", { fg = c.base0F })
    highlight("BlinkCmpKindConstant", { fg = c.base09 })
    highlight("BlinkCmpKindMethod", { fg = c.base0D })
    highlight("BlinkCmpSource", { bg = c.base00 })
    highlight("BlinkPairsYellow", { fg = c.base0A })
    highlight("BlinkPairsPurple", { fg = c.base0E })
    highlight("BlinkPairsCyan", { fg = c.base0C })

    -- NvimTree
    highlight("NvimTreeImageFile", { fg = c.base0C })
    highlight("NvimTreeFolderIcon", { fg = c.base0C })
    highlight("NvimTreeWinSeparator", { fg = c.base00, bg = c.base00 })
    highlight("NvimTreeFolderName", { fg = c.base09 })
    highlight("NvimTreeIndentMarker", { fg = c.base02 })
    highlight("NvimTreeEmptyFolderName", { fg = c.base0F })
    highlight("NvimTreeOpenedFolderName", { fg = c.base0F })
    highlight("NvimTreeNormal", { fg = c.base04, bg = c.base00 })

    -- Gitsigns
    highlight("GitSignsCurrentLineBlame", { link = "Comment" })
    highlight("GitSignsAdd", { fg = c.base0B })
    highlight("GitSignsChange", { fg = c.base09 })
    highlight("GitSignsDelete", { fg = c.base08 })
    highlight("GitSignsAddNr", { fg = c.base0B })
    highlight("GitSignsChangeNr", { fg = c.base09 })
    highlight("GitSignsDeleteNr", { fg = c.base08 })
    highlight("GitSignsAddLn", { fg = c.base0B })
    highlight("GitSignsChangeLn", { fg = c.base09 })
    highlight("GitSignsDeleteLn", { fg = c.base08 })

    -- StatusLine
    highlight("StatusReplace", { fg = c.base00, bg = c.base08 })
    highlight("StatusInsert", { fg = c.base00, bg = c.base0C })
    highlight("StatusVisual", { fg = c.base00, bg = c.base0E })
    highlight("StatusTerminal", { fg = c.base00, bg = c.base0B })
    highlight("StatusNormal", { fg = c.base00, bg = c.base0F })
    highlight("StatusCommand", { fg = c.base00, bg = c.base0D })

    -- LuaLine
    highlight("LuaLineNormalA", { fg = c.base00, bg = c.base0D, bold = true })
    highlight("LuaLineNormalB", { fg = c.base05, bg = c.base00 })
    highlight("LuaLineNormalC", { fg = c.base05, bg = c.base00 })
    highlight("LuaLineInsertA", { fg = c.base00, bg = c.base0B, bold = true })
    highlight("LuaLineVisualA", { fg = c.base00, bg = c.base0E, bold = true })
    highlight("LuaLineReplaceA", { fg = c.base00, bg = c.base08, bold = true })

    -- Snacks
    highlight("SnacksPicker", { fg = c.base05, bg = c.base00 })
    highlight("SnacksPickerBorder", { fg = c.base01 })
    highlight("SnacksPickerMatch", { fg = c.base0A, bold = true })
    highlight("SnacksPickerPrompt", { fg = c.base0C })
    highlight("SnacksPickerGitStatusAdded", { fg = c.base07 })
    highlight("SnacksPickerGitStatusModified", { fg = c.base09 })
    highlight("SnacksPickerGitStatusStaged", { fg = c.base0E })
    highlight("SnacksInputBorder", { fg = c.base01 })
    highlight("SnacksInputPrompt", { fg = c.base01 })
    highlight("SnacksInputTitle", { fg = c.base0D })
    highlight("SnacksInputIcon", { fg = c.base0C })
    highlight("SnacksIndent", { fg = c.base01 })
    highlight("SnacksIndentScope", { fg = c.base03 })
    highlight("SnacksPickerDirectory", { fg = c.base05 })

    -- Incline
    highlight("InclineNormal", { fg = c.base05, bg = c.base02 })
    highlight("InclineNormalNC", { fg = c.base06, bg = c.base01 })

    -- Terminal colors
    vim.g.terminal_color_0 = c.base01
    vim.g.terminal_color_1 = c.base0B
    vim.g.terminal_color_2 = c.base0E
    vim.g.terminal_color_3 = c.base0D
    vim.g.terminal_color_4 = c.base09
    vim.g.terminal_color_5 = c.base0F
    vim.g.terminal_color_6 = c.base08
    vim.g.terminal_color_7 = c.base05
    vim.g.terminal_color_8 = c.base03
    vim.g.terminal_color_9 = c.base0B
    vim.g.terminal_color_10 = c.base0E
    vim.g.terminal_color_11 = c.base0D
    vim.g.terminal_color_12 = c.base09
    vim.g.terminal_color_13 = c.base0F
    vim.g.terminal_color_14 = c.base07
    vim.g.terminal_color_15 = c.base06
  '';
}
