-- Load all plugin configurations
require("plugins.snacks-nvim")
require("plugins.incline")
require("plugins.lualine")
require("plugins.nvim-web-devicons")
require("plugins.nvim-highlight-colors")
require("plugins.fidget")
require("plugins.nvim-lspconfig")
require("plugins.nvim-treesitter")
-- require("plugins.filetypes")
require("plugins.gitsigns")
require("plugins.nvim-lint")
require("plugins.conform")
require("plugins.codecompanion")
require("plugins.tmux")
require("plugins.vim-sleuth")
require("plugins.blink-cmp")
require("plugins.luasnip")
require("plugins.copilot")
require("plugins.blink-pairs")
