---
name: Lint & Format
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore: [.github/**, assets/**, notes/**, README.md]
jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    outputs:
      lint-success: ${{ steps.result.outputs.lint }}
      format-success: ${{ steps.result.outputs.format }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run statix linter
        run: |
          echo "Linting Flake..."
          if nix run nixpkgs#statix -- check .; then
            echo "lint=true" >> $GITHUB_ENV
          else
            echo "lint=false" >> $GITHUB_ENV
            exit 1
          fi
      - name: Run nixfmt format
        run: |
          echo "Format Flake..."
          if nix run nixpkgs#nixfmt-rfc-style -- check .; then
            echo "format=true" >> $GITHUB_ENV
          else
            echo "format=false" >> $GITHUB_ENV
            exit 1
          fi
      - name: Determine lint result
        id: result
        run: |-
          echo "lint=${{ env.lint }}" >> $GITHUB_OUTPUT
          echo "format=${{ env.format }}" >> $GITHUB_OUTPUT
