---
name: Statix Lint
on:
  push:
    branches: [main]
    paths-ignore: [.github/**, assets/**, notes/**, README.md]
jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    outputs:
      lint-success: ${{ steps.result.outputs.success }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run statix linter
        run: |
          echo "Linting Flake..."
          if nix run nixpkgs#statix -- check .; then
            echo "success=true" >> $GITHUB_ENV
          else
            echo "success=false" >> $GITHUB_ENV
            exit 1
          fi
      - name: Determine lint result
        id: result
        run: echo "result=${{ env.success }}" >> $GITHUB_OUTPUT
