require("neo-tree").setup({
	close_if_last_window = true,
	popup_border_style = "rounded",
	enable_git_status = true,
	git_status_async = true,
	enable_diagnostics = false,
	hide_root_node = true,
	open_files_do_not_replace_types = {
		"terminal",
		"trouble",
		"qf",
	},
	sources = {
		"filesystem",
	},
	source_selector = {
		winbar = false,
		statusline = false,
		sources = {
			{ source = "filesystem" },
		},
	},
	default_component_configs = {
		indent = {
			indent_size = 2,
			padding = 1,
			with_markers = true,
			indent_marker = "│",
			last_indent_marker = "└",
			highlight = "NeoTreeIndentMarker",
			with_expanders = false,
			expander_collapsed = "",
			expander_expanded = "",
			expander_highlight = "NeoTreeExpander",
		},
		icon = {
			folder_closed = "",
			folder_open = "",
			folder_empty = "",
			default = "",
			highlight = "NeoTreeFileIcon",
		},
		name = {
			trailing_slash = false,
			use_git_status_colors = true,
		},
		git_status = {
			symbols = {
				added = "",
				deleted = "",
				modified = "",
				renamed = "➜",
				untracked = "★",
				ignored = "◌",
				unstaged = "✗",
				staged = "✓",
				conflict = "",
			},
		},
	},
	window = {
		position = "left",
		width = 35,
		mapping_options = {
			noremap = true,
			nowait = true,
		},
		mappings = {
			["<2-LeftMouse>"] = "open",
			["<cr>"] = "open",
			["o"] = "open",
			["S"] = "open_split",
			["s"] = "open_vsplit",
			["C"] = "close_node",
			["<bs>"] = "navigate_up",
			["."] = "set_root",
			["H"] = "toggle_hidden",
			["R"] = "refresh",
			["\\"] = "fuzzy_finder",
			["f"] = "filter_on_submit",
			["<c-x>"] = "clear_filter",
			["a"] = "add",
			["d"] = "delete",
			["r"] = "rename",
			["y"] = "copy_to_clipboard",
			["x"] = "cut_to_clipboard",
			["p"] = "paste_from_clipboard",
			["c"] = "copy",
			["m"] = "move",
			["q"] = "close_window",
		},
	},
	filesystem = {
		hijack_netrw_behavior = "open_current",
		use_libuv_file_watcher = true,
		follow_current_file = {
			enabled = true,
			leave_dirs_open = true,
		},
		filtered_items = {
			visible = false,
			hide_dotfiles = false,
			hide_gitignored = false,
			hide_by_name = {
				".DS_Store",
				"thumbs.db",
				"__pycache__",
				"node_modules",
			},
			hide_by_pattern = {
				"*.meta",
				"*/src/*/tsconfig.json",
			},
			always_show = {
				".gitignored",
			},
			never_show = {
				".DS_Store",
				"thumbs.db",
			},
			never_show_by_pattern = {
				".null-ls_*",
			},
		},
	},
	git_status = {
		window = {
			position = "float",
			mappings = {
				["A"] = "git_add_all",
				["gu"] = "git_unstage_file",
				["ga"] = "git_add_file",
				["gr"] = "git_revert_file",
				["gh"] = "git_commit",
				["gp"] = "git_push",
				["gg"] = "git_commit_and_push",
			},
		},
	},
})
